### ISSUE TITLE
Gramática - Introducción Series de Tiempo

### ISSUE THREAD

**Issue by felipearroyomz** [sbohorquez/Econometria2#102]
Profe, en la diapositiva No. 52.7, se menciona la prueba KPSS en minúsculas, debería estar escrita en mayusculas pues son nombres, tal cual se hizo con las pruebas PP y ADF.

**Comment by felipearroyomz** [comment]
Profe, soy Hernan Felipe Arroyo Meza y @felipearroyomz es mi usuario de Github.

Gracias.

**Comment by sbohorquez** [comment]
Se hizo la corrección, gracias
