### ISSUE TITLE
Sugerencia Gráfica - Modelos Lineales Dinámicos

### ISSUE THREAD

**Issue by felipearroyomz** [sbohorquez/Econometria2#105]
Desde mi punto de vista, seria ideal (al igual que se hizo con los modelos AR), disponer de gráficas de ACF en el apartado de los modelos MA(1) y MA(Q), para poder identificar gráficamente los ordenes de modelos de medias móviles (pags. 29-48).

**Comment by sbohorquez** [comment]
el issue #47 dice eso, se deja abierta hasta incluirla
