### ISSUE TITLE
Problema de selección del modelo 

### ISSUE THREAD

**Issue by jfcardonaz** [sbohorquez/Econometria2#106]
En un proceso de análisis del comportamiento a través del tiempo de una variable,  es muy importante saber escoger bien el modelo con se quiere representar el comportamiento de dicho proceso. No obstante,  este proceso de elección recae sobre el interesado en hacer el análisis y por tanto, la elección del modelo recae sobre un cierto sesgo conceptual que puede llevar a sobre ajustes del modelo; ¿Cómo afecta este sesgo en el resultado del modelo seleccionando? Los criterios de información nos ayudan a seleccionar el mejor modelo de todos los que el analista considera, peor ¿Cómo se puede asegurar con cierto grado de certeza que ese modelo seleccionado es en realidad el que me explica la realidad del comportamiento de la variable?

**Comment by sbohorquez** [comment]
Los criterios de selección están basados en el supuesto que existe un modelo verdadero que describe el proceso generador de datos, y tanto el AIC como el BIC encuentran este modelo verdadero entre todos los modelos asintoticamente, es decir si tenemos una muestra infinitamente grande. Entonces, si dejamos que los criterios de selección escojan el modelo deberíamos de escoger un modelo verdadero y no uno basado simplemente en lo que considere el invetigador.
