### ISSUE TITLE
Sugerencia Criterios - Modelos Lineales Dinámicos

### ISSUE THREAD

**Issue by felipearroyomz** [sbohorquez/Econometria2#107]
Desde mi punto de vista, en la página 74.1 seria idóneo identificar y plasmar en la diapositiva los resultados de las pruebas AIC y BIC, es decir, saber cuál escoger, si el modelo de menor valor o el más cercano a cero.

**Comment by sbohorquez** [comment]
Se resalto que se debe Minimizar el criterio
