### ISSUE TITLE
[Math Processing Error] - Modelos Dinámicos con Variables Exógenas

### ISSUE THREAD

**Issue by felipearroyomz** [sbohorquez/Econometria2#109]
No sé si solo sea a mí, pero en la diapositiva No. 13, hay tres términos en el primer párrafo que me aparecen con [Math Processing Error], seria ideal corregirlo o el saber por qué sale eso en navegador Safari.

**Comment by sbohorquez** [comment]
No me aparece ese error, y no he sido capaz de reproducirlo dado que no uso Safari
