### ISSUE TITLE
Presentación paseo aletorio

### ISSUE THREAD

**Issue by felipesierram** [sbohorquez/Econometria2#114]
En la presentación se expone la formula de un paseo aleatorio el cual es: "Xt = Xt-1 + Et"

Sugiero que sería bueno mostrar que un paseo aleatorio en fórmula es la diferenciación de un ruido blanco como método de comprendimiento de las fórmulas "Xt = Et"

**Comment by sbohorquez** [comment]
Eso esta en la diapositiva 35
