### ISSUE TITLE
Presentación AR(P) y MA(Q)

### ISSUE THREAD

**Issue by felipesierram** [sbohorquez/Econometria2#115]
Profe, considero que sería bueno (si bien ya se ve en la monitoria la parte en R) una gráfica de un autocorrelograma para AR(P) y un autocorrelograma parcial  para MA(Q). esto con el propósito de entender de manera más clara la interpretación de estos modelos

**Comment by sbohorquez** [comment]
Esta en el issue #47 para incluir
