### ISSUE TITLE
Modelos ADL ejemplos

### ISSUE THREAD

**Issue by felipesierram** [sbohorquez/Econometria2#117]
En la diapositiva 21 donde se ven los casos especiales de modelos ADL, sería bueno utilizar ejemplos para demostrar como aplicar estos casos con las fórmulas ya vistas.

Esto sería así: Ejemplo -> A partir de un modelo ADL (2,2) cuáles serían las condiciones y resultados a aplicar en este modelo para se convierta en un modelo estático con errores AR(1) donde β1=−ϕ1β0

**Comment by sbohorquez** [comment]
SE hace para el ADL(1,1), propones poner más ejemplos?
