### ISSUE TITLE
Definición de modeloro AR(P)

### ISSUE THREAD

**Issue by DiegoaQuintero** [sbohorquez/Econometria2#14]
En la definición del modelo AR(P) la formula deberia estar escrita como $X_t=\phi_1X_{t-1}+\phi_2X_{t-2}+...+\phi_pX_{t-p}+\varepsilon_t$ Esto por que el epsilon t no multiplica, debe estar sumando.

**Comment by sbohorquez** [comment]
Corregido en las diapositivas
