### ISSUE TITLE
Bases de datos para R

### ISSUE THREAD

**Issue by dialazu** [sbohorquez/Econometria2#146]
Al intentar replicar los ejemplos de R para los temas vistos en clase (OLS, GLS) he evidenciado que en los códigos de R dados de ejemplos las bases de datos son cargadas desde archivos del computador y estas bases de datos no se encuentran montadas en los archivos de Github, esto hace un poco más difícil la realización de los ejemplos.

**Comment by dialazu** [comment]
https://wps.pearsoned.com/aw_stock_ie_3/178/45691/11696965.cw/index.html

**Comment by sbohorquez** [comment]
Hola, ya subi la base de datos.
