### ISSUE TITLE
Error ortográfico.

### ISSUE THREAD

**Issue by dialazu** [sbohorquez/Econometria2#148]
En la diapositiva 7 de "Introducción a Series de Tiempo" falta una tilde en: i la variable **esta** medida anualmente t−1
t-1 es el año anterior, pero si **esta** medida mensualmente, t−1 es el mes anterior. Según entiendo el contexto, esto debería ser **está** en ambos casos.

**Comment by dialazu** [comment]
En la diapositiva 19 también falta una tilde en la parte "En el caso especial de la distribución normal, estacionariedad débil **si** implica estacionariedad estricta.", este si debería ir tildado ya que en este caso no tiene función de condicional sino de aprobación.

**Comment by sbohorquez** [comment]
Se hizo la corrección, gracias.
