### ISSUE TITLE
Falta título

### ISSUE THREAD

**Issue by dialazu** [sbohorquez/Econometria2#149]
En las diapositivas de "Introducción Series de Tiempo", la diapositiva 14.1, la cual corresponde a la primera diferencia de logaritmos  no tiene título, por lo cual pareciera que fuese una continuación del operador de diferencia. Mientras que la diapositiva 14.2 sí lleva el título correspondiente al cambio porcentual.

**Comment by sbohorquez** [comment]
Es una continuación del operador de diferencias, el cambio porcentual es la demonstración de lo que se dice.
