### ISSUE TITLE
Posible error en la presentación Introducción Series de Tiempo

### ISSUE THREAD

**Issue by dialazu** [sbohorquez/Econometria2#150]
Según mi análisis, en la diapositiva 32, al iterar hasta el periodo n, la esperanza del error no se iría hasta el periodo n sino hasta el periodo (n-1), por cual la ecuación Var(xt)=E[x2t−n]+E[ε2t−n]+⋯+E[ε2t−1]+E[ε2t] quedaría de la siguiente forma:

Var(xt)=E[x2t−n]+E[ε2t−(n-1)]+⋯+E[ε2t−1]+E[ε2t]

**Comment by sbohorquez** [comment]
Correcto, se hace la corrección. Gracias
