### ISSUE TITLE
Duda "Introducción Series de Tiempo"

### ISSUE THREAD

**Issue by dialazu** [sbohorquez/Econometria2#151]
En la diapositiva 36, al iterar el proceso de Wt, ¿no debería este llegar hasta el X1?, es decir, 

¿ x_t=w_t+w_t−1+w_t−2+w_t−3+…w_t-(n+1)+x_1  ?

**Comment by sbohorquez** [comment]
No necesariamente, llega hasta un valor rezagado en el tiempo infinitos periodos, no suponemos que empieza en 1, puede empezar en cualquier momento.
