### ISSUE TITLE
Actualización de las primeras páginas

### ISSUE THREAD

**Issue by Lfsanchezc** [sbohorquez/Econometria2#153]
Profe una sugerencia, es algo sumamente sencillo. Cambiar el nombre de la escuela en las presentaciones a "Escuela de Finanzas, Economía y Gobierno", pues aparece el nombre anterior de "Escuela de Economía y Finanzas"

**Comment by sbohorquez** [comment]
Tenés toda la razón. Se realiza la corrección gracias
