### ISSUE TITLE
Pregunta Variables Exógenas Diap. 23

### ISSUE THREAD

**Issue by svargasj** [sbohorquez/Econometria2#158]
¿Me podría volver a explicar que quiere decir que si la condición no se cumple xt se vuelve explosivo?

**Comment by dialazu** [comment]
Para que este proceso sea estacionario, cada uno de los procesos que hacen parte del modelo debe ser estacionario. Es decir para que xt sea estacionario, no solamente el phi debe ser en valor absoluto menor a 1, sino que el proceso de Zt también debe ser estacionario. Por ende si phi es menor a 1 en valor absoluto, esto no nos garantiza per se que el proceso sea estacionario, sin imponer otra condición en Zt. Sin embargo, si phi es mayor a 1, esto sí significaría que el proceso no es estacionario porque pasaría lo mismo que pasa en un proceso ar(1) cuando el phi es mayor a 1 (se vuelve explosivo porque el limite de phi cuando n tiende a infinito no converge a 0)

**Comment by sbohorquez** [comment]
> Para que este proceso sea estacionario, cada uno de los procesos que hacen parte del modelo debe ser estacionario. Es decir para que xt sea estacionario, no solamente el phi debe ser en valor absoluto menor a 1, sino que el proceso de Zt también debe ser estacionario. Por ende si phi es menor a 1 en valor absoluto, esto no nos garantiza per se que el proceso sea estacionario, sin imponer otra condición en Zt. Sin embargo, si phi es mayor a 1, esto sí significaría que el proceso no es estacionario porque pasaría lo mismo que pasa en un proceso ar(1) cuando el phi es mayor a 1 (se vuelve explosivo porque el limite de phi cuando n tiende a infinito no converge a 0)

Esta es la respuesta
