### ISSUE TITLE
Errores Modelos lineales dinámicos

### ISSUE THREAD

**Issue by svargasj** [sbohorquez/Econometria2#159]
¿Es posible separar la información de las diapositivas #4, 62,2 y 62,3 del tema de modelos lineales dinámicos en más diapositivas? ya que no se puede ver toda la demostración sin tener que reducir en tamañode la pantalla

También podría añadirse ejemplos cotidianos para entender mejor la teoría?

**Comment by sbohorquez** [comment]
Se hizo la corrección de las diapositivas. Se considera el comentario sobre ejemplos aplicados.
