### ISSUE TITLE
Duda en diapositiva 12 de Modelos lineales dinámicos

### ISSUE THREAD

**Issue by Alejaarte** [sbohorquez/Econometria2#16]
En la dispositiva 12 en "Dado que , E[\varepsilon _{t}x_{t-j}]=0 " se debería aclarar que es cuando j\geq 1 . ¿Esto es debido a que los errores son independientes de las variables regresoras cuando están en diferentes períodos? De esta manera se podría considerar que:
E(\varepsilon _{t}x_{t-j})=E(\varepsilon _{t})*E(x_{t-j})=0*E(x_{t-j})=0
¿Es esto incorrecto o hay otra razón?

**Comment by sbohorquez** [comment]
Se incluyo la corrección de  $j \geq 1$ en la diapositiva 12. 

Sí, es cero porque son independientes cuando la x esta rezagada.
