### ISSUE TITLE
Corrección diapositiva #20 en presentación Auto-Correlación.

### ISSUE THREAD

**Issue by FranciscoBotero** [sbohorquez/Econometria2#160]
En la parte de Yule-Walker test creo que hay un error en la fórmula que nos puede confundir ya que no está en términos generales. Creo que se debe cambiar el número 1 por la letra j. Adjunto dirección de la foto.

![Captura de pantalla 2022-09-05 221919](https://user-images.githubusercontent.com/110293399/188540030-310b9b96-fe16-4f63-8fdc-315dea3c165f.png)

**Comment by sbohorquez** [comment]
Correcto, se hizo la corrección. Gracias
