### ISSUE TITLE
Recomendación diapositiva #29 presentación modelos dinámicos con variables exógenas.

### ISSUE THREAD

**Issue by FranciscoBotero** [sbohorquez/Econometria2#161]
Me parece que para mayor comprensión se debería cambiar el párrafo donde se aclara que los estimadores calculados por R no tienen ningún problema. Este párrafo se podría ubicar mejor luego de que se han explicado las razones por las cuales dichos estimadores no tienen problemas de interpretación. Creo que estaría bien ubicado en la diapositiva 32. Adjunto foto señalando el párrafo.

![image](https://user-images.githubusercontent.com/110293399/188540992-5013030b-0b92-494c-8575-e18cb87c9ebb.png)

**Comment by sbohorquez** [comment]
Se hizo la corrección, gracias
