### ISSUE TITLE
Recomendación aplicación práctica de los modelos.

### ISSUE THREAD

**Issue by FranciscoBotero** [sbohorquez/Econometria2#162]
Creo que ya se ha dicho repetidamente, pero me parece importante que, así como se tiene en las primeras diapositivas (MCO y MCG), se puedan proponer diferentes aplicaciones con ejemplos de códigos en R, con el fin de afianzar habilidades tanto prácticas en el uso del programa como de interpretación de los diferentes modelos, test, etc. que conjugue la habilidad práctica con el conocimiento teórico.

**Comment by sbohorquez** [comment]
Para esto están las monitorias. Los códigos también están disponibles en interactiva. Explorare adjuntarlas al final.
