### ISSUE TITLE
MA(1)

### ISSUE THREAD

**Issue by Fddavidh24** [sbohorquez/Econometria2#163]
Hola profe.
           Quizás sea una mala apreciación de mi parte pero tengo una duda.
           Para un modelo MA(1) cuál es la condición impuesta si es estacionario débil.

**Comment by dialazu** [comment]
Un proceso MA por definición siempre es estacionario. Por lo cual a diferencia de los procesos AR, estos no necesitan de la imposición de un supuesto para garantizar que sean estacionarios.

**Comment by sbohorquez** [comment]
> Un proceso MA por definición siempre es estacionario. Por lo cual a diferencia de los procesos AR, estos no necesitan de la imposición de un supuesto para garantizar que sean estacionarios.

Esta es la respuesta
