### ISSUE TITLE
Interpretación en Newey West

### ISSUE THREAD

**Issue by Fddavidh24** [sbohorquez/Econometria2#164]
En mis comentarios del Quiz 1, al parecer me equivoque en la interpretación del NW. En ese sentido, me gustaría leer una interpretación general .

Muchas Gracias.

**Comment by sbohorquez** [comment]
El Newey-West estima errores estandares robustos a auto-correlación y heteroscedasticidad. Así si los errores estandares son distintos a los del MCO es porque existe alguno de lestos problemas en los datos.
