### ISSUE TITLE
Criterios de selección 

### ISSUE THREAD

**Issue by Fddavidh24** [sbohorquez/Econometria2#165]
Cuando se analiza el BIC y el AIC, si los resultados son sustancialmente diferentes, Con cuál nos quedamos o que podríamos concluir.

**Comment by dialazu** [comment]
En clase lo que dijo el profesor es que en general si estos dos no son congruentes, es más recomendable creerle al BIC debido a que este penaliza de mayor manera la sobre parametrización.

**Comment by sbohorquez** [comment]
> En clase lo que dijo el profesor es que en general si estos dos no son congruentes, es más recomendable creerle al BIC debido a que este penaliza de mayor manera la sobre parametrización.

Esto es correcto.
