### ISSUE TITLE
Prueba de D-F Aumentado

### ISSUE THREAD

**Issue by DiegoaQuintero** [sbohorquez/Econometria2#17]
La formula de Dickey (1984) deberia estar escrita como $\Delta x_t = \beta x_{t-1}+\phi´_1\Delta x_{t-1}+\phi´_2\Delta x_{t-2}+...+\phi´_{p-1}\Delta x_{t-(p-1)}+\varepsilon_t$

**Comment by DiegoaQuintero** [comment]
La formula ya esta modificada en el .Rmd pero no en el .html.

**Comment by sbohorquez** [comment]
Se actualizo el knit del html para reflejar el cambio
