### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by MARIAPAULACASTELBLANCO** [sbohorquez/Econometria2#178]
Como recomendación considero importante mayor información interactiva en las presentaciones que ayuden a comprender los temas de una manera más dinámica, ya que a pesar de que las demostraciones son fundamentales, existen otras formas de aprendizaje más visuales que pueden complementar los temas de la asignatura.

**Comment by sbohorquez** [comment]
Cómo cuales?

**Comment by MARIAPAULACASTELBLANCO** [comment]
Más ejemplos analíticos de los modelos vistos, realización de casos Harvard, etc.

**Comment by sbohorquez** [comment]
Los casos Harvard, son estudios de caso, una metodologia distinta a la econometría. La realización de casos analiticos se deja como comentario para realizar en las monitorias.
