### ISSUE TITLE
Pregunta teoría de mercados eficientes. 

### ISSUE THREAD

**Issue by juanfrpoy** [sbohorquez/Econometria2#179]
Buenas tardes, tengo una duda con respecto al paseo aleatorio y la teoría de los mercados eficientes. ¿El precio de una acción obligatoriamente tiene que cumplir la ley de los mercados eficientes donde no hay autocorrelación? suponiendo que no es obligatorio, ¿la autocorrelación permite hacer predicciones sobre el precio futuro de una acción?

**Comment by sbohorquez** [comment]
La teoría de mercados eficientes no necesariamente se cumple para todas las acciones, si no se cumple entonces se podría usar el pasado de la serie para hacer predicciones.

**Comment by juanfrpoy** [comment]
Visto esto gráficamente en un ACF, ¿se entiende que si la serie presenta rezagos estadísticamente significativos se presenta autocorrelación?

**Comment by sbohorquez** [comment]
Si
