### ISSUE TITLE
Aclaración parciales de práctica

### ISSUE THREAD

**Issue by juanfrpoy** [sbohorquez/Econometria2#186]

**Comment by juanfrpoy** [comment]
Me parece importante aclarar que las tablas con los modelos en los parciales de práctica no se realizan en R (Probablemente es en Python) y los valores se ubican diferentes a lo acostumbrado en R, lo cual puede causar confusión en la práctica.

**Comment by sbohorquez** [comment]
Todo esta hecho en R. La presentación cambia porque se pone en tablas tipo articulo, pero todo el código es en R.
