### ISSUE TITLE
ARIMA con tendencia e intercepto.

### ISSUE THREAD

**Issue by jdrengifoc** [sbohorquez/Econometria2#19]
Se que se puede simular un ARIMA con la siguiente función, `arima.sim(list(order = c(1,0,0), ar = 0.2), n = 100)`
¿Es posible usar esa función para simular un ARIMA con tendencia e intercepto?

**Comment by sbohorquez** [comment]
Dado que la constante y tendencia son completamente deterministicas se pueden agregar a la simulación directamente: 
delta <- 1
alpha <- 0.5
t <- seq(1:100)
delta + alpha*t + arima.sim(list(order = c(1,0,0), ar = 0.2), n = 100)

**Comment by sbohorquez** [comment]
Revisando el comando arima.sim puedes incluir un intercepto con la opción mean, donde mean es la esperanza del proceso. La tendencia si debe ser agregada despues, ver: https://stackoverflow.com/questions/67905933/use-arima-sim-to-simulate-arima-1-1-1-with-drift-in-r

**Comment by sbohorquez** [comment]
Cierro el issue por inactividad.
