### ISSUE TITLE
Corrección Diapositivas Modelos ARIMA

### ISSUE THREAD

**Issue by mapelaezr** [sbohorquez/Econometria2#23]
Buenas tardes profe, una pequeña corrección.

En las diapositivas mencionadas, en la diapositiva especia donde se expone el operador de rezagos para los procesos MA(q), falta un L^q en ultimo termino dentro de los paréntesis.

Feliz semana.

![image](https://user-images.githubusercontent.com/98849410/155213008-0472e13b-f9c3-43f5-8fba-2c652285a137.png)

**Comment by sbohorquez** [comment]
Se hizo la corrección en las diapositvas. Gracias
