### ISSUE TITLE
duda modelos Arima

### ISSUE THREAD

**Issue by camilahm2022** [sbohorquez/Econometria2#24]
Buenas tardes,
Tengo una duda, sobre las correlaciones. ¿se necesita la matriz para poder hallar las correlaciones asi tengamos los Phi (Φ), o no hay necesidad alguna?
feliz día

**Comment by sbohorquez** [comment]
Hola,

No es estrictamente necesario usar las matrices, pero como las correlaciones son funciones de correlaciones pasadas el calculo se hace más fácil si usamos las matrices.

**Comment by camilahm2022** [comment]
Muchas gracias!
