### ISSUE TITLE
Proceso estacionario débil de los AM (q)

### ISSUE THREAD

**Issue by jfcardonaz** [sbohorquez/Econometria2#31]
¿Al no tener que imponer restricciones sobre el parámetro para obtener la media, varianza o auto-covarianzas, los modelos AM son sesgados o permiten la sobreestimación de los parámetros regresores?

**Comment by sbohorquez** [comment]
Hola,

Tienen un problema de identificación, en general pueden haber multiples soluciones para theta y sigma que describen el proceso. Por lo cual, a la hora de estimar, si tenemos que imponer restricciones. Esto no lo alcanzamos a cubrir en este curso, pero lo puedes ver en: Uriel y Peiro (2000) Sección 3.2.

**Comment by sbohorquez** [comment]
Cierro por inactividad
