### ISSUE TITLE
Numeración

### ISSUE THREAD

**Issue by Afelipe-Ruiz** [sbohorquez/Econometria2#32]
Profe, otra recomendación es que enumeres los slides, será más fácil para decirte, en que parte de la presentación está el error y para nos facilitará encontrar las diapositivas que no copiamos en clase.
Muchas gracias

**Comment by sbohorquez** [comment]
Hola,

Tratare de incluir la numeraqción en las diapositvas, queda abierto hasta que lo haga.

**Comment by sbohorquez** [comment]
Numeración agregada a diapositivas.
