### ISSUE TITLE
Índice y Numeración

### ISSUE THREAD

**Issue by emarc272** [sbohorquez/Econometria2#35]
Profe, tengo una sugerencia y es con respecto a que se cree una diapositiva de índice que diga en que diapositiva empieza cada subtema del tema de la clase que nos puede servir para tener una mejor guía.

**Comment by sbohorquez** [comment]
Lo incluire en las diapositvas, queda abierto hasta que lo haga.

**Comment by sbohorquez** [comment]
Un menu ha sido agregado a las diapositvas para ver en que diapositva empieza cada sección.
