### ISSUE TITLE
PRESENTACIÓN MCO

### ISSUE THREAD

**Issue by ZeinDaher10** [sbohorquez/Econometria2#37]
Profe hola, 
Es que repasando MCO llegué a la Diapositiva de B (~) VIRGULILLA. No recuerdo que era lo que quería decir esto o por qué se usaba? Por qué en la diapositiva dice que su varianza es mayor a la de un B^ que es el que siempre usamos, entonces para que el de virgulilla?

**Comment by sbohorquez** [comment]
Es otro estimador cualquiera. Es la prueba que MCO es el MELI vista en Econometría 1.
