### ISSUE TITLE
PRESENTACIÓN SERIES DE TIEMPO - Ortografía y Redacción.

### ISSUE THREAD

**Issue by ZeinDaher10** [sbohorquez/Econometria2#38]
En la segunda diapositiva cuando se introduce el tema:

- "ó ¿Cual es la mejor predicción del valor de una variable en el futuro?"

Sería mejor dejarlo sin la "ó", pues queda mejor:

¿Cuál es la mejor predicción del valor de una variable en el futuro?

También recordar ponerle tilde a la palabra "Cuál" pues al ser pregunta lleva tilde.

**Comment by sbohorquez** [comment]
Gracias por las correcciones, se hicieron los cambios.
