### ISSUE TITLE
Presentación Series de Tiempo - Pregunta

### ISSUE THREAD

**Issue by ZeinDaher10** [sbohorquez/Econometria2#41]
Profe en la parte del operador de diferencia nosotros como hemos visto en clase usamos el:Δn=1−L^n y lo desarrollamos. Pero también mencionamos el Δ^n=(1−L)^n, ese para qué se usa?

**Comment by sbohorquez** [comment]
Hola, El operador Delta^n se usa para sacar diferencias de diferencias, esto es usado cuando la integración es de orden superior a 1. En economía en general las series son integradas de orden 1, pero existen proceso en finanzas, por ejemplo precio de criptomonedas, que pueden ser integradas de orden 2, lo que haría necesario sacar la segunda diferencia.

**Comment by sbohorquez** [comment]
Cierro issue por inactividad
