### ISSUE TITLE
Cohesión Modelos Dinámicos 

### ISSUE THREAD

**Issue by emarc272** [sbohorquez/Econometria2#44]
En las diapositivas de Modelos Dinámicos con varias variables especialmente en la parte del modelo ADL cuando se obtiene el modelo en primeras diferencias se hace una claridad de que se debe testear contra otros modelos.

Se especifica de la siguiente manera: 
"antes de aceptar cualquiera de estos casos especiales, deberíamos de testearlos contra el modelo ADL (1,1) general."

La palabra "de" después de la coma se debe eliminar ya que no tiene cohesión y tendría que quedar de la siguiente manera:
"antes de aceptar cualquiera de estos casos especiales, deberíamos testearlos contra el modelo ADL (1,1) general."

**Comment by sbohorquez** [comment]
Se hizo la corrección, gracias.
