### ISSUE TITLE
Estacionariedad

### ISSUE THREAD

**Issue by Afelipe-Ruiz** [sbohorquez/Econometria2#49]
Profe en la parte de estacionariedad, en las diapositivas de series de tiempo sería bueno poner en un slide este segmento del libro que me parece muy bien explicado acerca de proceso de series de tiempo estacionario.

"Proceso de series de tiempo estacionario: es aquel que su distribución de probabilidad conjunta se mantiene constante durante el tiempo
Si se toma cualquier cualquier colección de variables aleatorias de la secuencia y se desplaza n periodos, la distribución de probabilidad conjunta debe permanecer inalterada" 
Quizás sirva para algunos compañeros que lo quieran tener un poco más claro el concepto cuando estén estudiando

**Comment by sbohorquez** [comment]
Hola, @Afelipe-Ruiz  me regalas la pagina y el libro para citarlo?

**Comment by Afelipe-Ruiz** [comment]
claro que si. 378 del libro de Wooldrige

**Comment by Afelipe-Ruiz** [comment]
Lo creo que lo parafrasee un poco

**Comment by sbohorquez** [comment]
Se hizo la adición, gracias.
