### ISSUE TITLE
Diapositiva

### ISSUE THREAD

**Issue by Afelipe-Ruiz** [sbohorquez/Econometria2#50]
![image](https://user-images.githubusercontent.com/98567630/156463539-987985dc-ea8d-413e-837d-0a55c72d5a6f.png)
Hola profe, en esta parte de la diapositiva de intro a las series de tiempo  yo pondría 

Original 
sigue una distribución normal, por lo cual p-values derivados de este supuesto estarían erróneos.

Recomendación
sigue una distribución normal, por lo cual los p-values derivados de este supuesto estarían erróneos.

**Comment by sbohorquez** [comment]
Se hizo la corrección, gracias
