### ISSUE TITLE
Tilde

### ISSUE THREAD

**Issue by Afelipe-Ruiz** [sbohorquez/Econometria2#51]
![image](https://user-images.githubusercontent.com/98567630/156463539-987985dc-ea8d-413e-837d-0a55c72d5a6f.png)

Hola profe, creo que en esta parte te faltó una tilde 

Original
MacKinnon (1996) derivo las probabilidades asociadas a las distribuciones de este parámetro a través de simulaciones. 

Recomendación
 MacKinnon (1996) derivó las probabilidades asociadas a las distribuciones de este parámetro a través de simulaciones.

**Comment by sbohorquez** [comment]
Se hizo la corrección, gracias
