### ISSUE TITLE
ModelosARIMA - Sección 4

### ISSUE THREAD

**Issue by jmocampoc13** [sbohorquez/Econometria2#57]
Hola profe,

Una duda la iteración del proceso de la varianza tiene hay un error?
Pensaría que en las líneas 76 sería E[\varepsilon_{t-(n-1)}^2 ] en lugar de E[\varepsilon_{t-n}^2 ]

\begin{align}
Var(x_t) & = \phi^{2n} E[x_{t-n}^2] + \phi^{2(n-1)} E[\varepsilon_{t-(n-1}^2 ] + \dots  + \\
& \phi^2 E[\varepsilon_{t-1}^2] + E[\varepsilon_t^2] \\

**Comment by sbohorquez** [comment]
Hola, tienes razón. Se cambio por lo propuesto.
