### ISSUE TITLE
Sugerencia ejemplo Modelo ARMAX

### ISSUE THREAD

**Issue by ValentinaAriasT** [sbohorquez/Econometria2#61]
Hola profe.

Podrías poner por favor al final de las diapositivas de Modelos dinámicos con variables exógenas, el ejemplo que mostraste al final de la clase de la demostración de ARMAX(1,1,1), con el fin de tener una mejor visualización de como hacer el modelo y tenerlo en cuenta para futuros ejercicios.

**Comment by sbohorquez** [comment]
Hola, se agrego el ejemplo al final.
