### ISSUE TITLE
DUDA operación de diferencia

### ISSUE THREAD

**Issue by cmorenob** [sbohorquez/Econometria2#62]
Hola profe,estoy repasando los primeros temas y en la diapositiva 13 de intro series de tiempo no me queda muy claro cuál  es el operador de diferencia  de n períodos y el de orden n, por lo que copié creo que el primero es el de n períodos que es en el que puedo "ir más lejos" y el segundo de orden n que dijiste que generalmente es de orden 1 o 2 (me corriges si no es así). Propongo depronto ponerle el título en negrilla con : y cada uno abajo del título para que quede más claro en la diapositiva. Gracias, quedo atenta a tu respuesta.

**Comment by sbohorquez** [comment]
Se cierra por inactividad
