### ISSUE TITLE
DUDA AIC Y BIC

### ISSUE THREAD

**Issue by cmorenob** [sbohorquez/Econometria2#63]
Hola profe, entiendo que en las diapositivas dices que cuando hay incongruencia entre el AIC y el BIC debemos priorizar elBIC, en la monitoría  Miguel mencionó algo de que era porque este penalizaba más el problema de muestras pequeñas, me podrías explicar eso bien porfa? gracias (si si es por esa razón me parecería bueno agregarlo a la diapositiva ya que no me queda muy claro "porque castiga mejor la relación número de parámetros y datos").

**Comment by sbohorquez** [comment]
Hola, la razón es que la penalidad del BIC es más grande que la del AIC, y depende de T no solo en el denominador sino también en el numerador. La penalidad del AIC es 2*k/T, mientras que el BIC es ln(T)*k/T, cuando T es mayor a 7 el ln(T) es mayor a 2. Y cuando T es pequeño, ln(T)/T es mas grande que cuando T es grande, por ejemplo si T=50 estao da 0.078 y si T=500 es 0.012, por lo cual castiga más cuando la muestra es pequeña

**Comment by cmorenob** [comment]
Ah listo profe ya entendí. Muchas gracias.
