### ISSUE TITLE
sugerencia modelos ARMA

### ISSUE THREAD

**Issue by cmorenob** [sbohorquez/Econometria2#64]
Hola profe, sería bueno agregar (como lo hiciste con los AR(1) ), más ejemplos de autocorrelogramas para diferenciar también los MA y los distintos ARMA(p,q) que podemos encontrar, Gracias.

**Comment by sbohorquez** [comment]
Hola, el issue #47 esta abierto con la misma propuesta. Dejo abierto el issue #47 hasta que lo haga y cierro este.
