### ISSUE TITLE
Sugerenecia caminata aleatoria

### ISSUE THREAD

**Issue by camilarestrepom** [sbohorquez/Econometria2#67]
Hola profe,
En la presentación de Introducción de Series de Tiempo al introducir el tema de la caminata aleatoria creo que es importante agregar una pagina donde se especifique que la caminata aleatoria es un caso especial de un AR(Q) en donde el phi es igual a 0 y que puede ser de cualquier orden, no solo AR(1).

**Comment by sbohorquez** [comment]
Hola Camila,

El paseo aleatorio es el caso especial que estamos viendo en esas diapositivas, si es de otro orden igual puede ser no estacionario, pero no lo llamamos paseo aleatorio.

**Comment by sbohorquez** [comment]
Se cierra por inactividad
