### ISSUE TITLE
Duda en supuestos MCO

### ISSUE THREAD

**Issue by camilarestrepom** [sbohorquez/Econometria2#7]
Hola profe,
tengo una duda en los supuestos MCO que salen en las diapositivas de Repaso MCO. En Econometria 1, los supuestos que utilizabamos para los estimadores eran:
1. Modelo de regresión lineal en parametros  
2. 2. valores fijos de X independientes al termino de error - cov(u,x)=0
3. El valor medio de la perturbarcion = 0 
4. La varianza del error constante (homoscedasticidad)
En estas diapositivas hay algunos supuestos similares pero otros son diferentes, como el del cuarto momento. Quisiera saber cual es la relación entre ambos supuestos o si debemos utilizar los nuevos que estamos viendo en clase.

**Comment by sbohorquez** [comment]
Hola Camila,

Los supuestos que yo pongo en las diapositivas son más generales, igual, mira que para encontrar el teorema de Gauss-Markov tenemos que hacer el supuesto de homoscedasticidad. Otra razón por la cual difieren es que en Econometría 1 siempre trabajan en corte transversal, mientra que yo pongo los supuestos basados en series de tiempo, por ejemplo defino la covarianza para periodos de tiempo.

**Comment by sbohorquez** [comment]
Cierro el issue, dado que no hubo más preguntas.
