### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Afelipe-Ruiz** [sbohorquez/Econometria2#80]
Profe, en al diapositiva 16 de modelos lineales dinámicos creo que hay un error.

Original

Con la auto-correlación podemos hacer el auto-correlograma el cual gráfica la auto-correlación en cada rezago. Observemos diferentes modelos AR(1) y las diferencia de sus auto-correlogramas teóricos.......
 
Sugerencia

Con la auto-correlación podemos hacer el auto-correlograma, el cual **grafica** la auto-correlación en cada rezago. Observemos diferentes modelos AR(1) y las diferencia de sus auto-correlogramas teóricos.......

**Comment by sbohorquez** [comment]
Se hizo la corrección, gracias
