### ISSUE TITLE
Error Redacción Presentación MCG (Diapositiva 8). 

### ISSUE THREAD

**Issue by ZeinDaher10** [sbohorquez/Econometria2#84]
El segundo bullet point dice: "Este supuesto requiere que los errores de la observación i no esta correlacionado con ningún regresor de otras observaciones."

Como se está hablando de LOS REGRESORES, considero que quedaría mejor en términos de redacción de la siguiente manera:

"Este supuesto requiere que los errores de la observación i NO ESTÉN  correlacionadoS con ningún regresor de otras observaciones."

**Comment by sbohorquez** [comment]
Se hizo la corrección, gracias
