### ISSUE TITLE
Redacción Presentación Auto Correlación (Diapositiva 17)

### ISSUE THREAD

**Issue by ZeinDaher10** [sbohorquez/Econometria2#85]
El contenido de esta diapositiva dice lo siguiente: "Podemos evitar hacer esta estimación no lineal, si hacemos test basándonos en la regresión de Gauss-Newton."

Entre la palabra "hacemos" y "test" debería de haber un conector. Por ejemplo: un

Así: "Podemos evitar hacer esta estimación no lineal, si hacemos un test basándonos en la regresión de Gauss-Newton."

**Comment by sbohorquez** [comment]
Se hizo la corrección, gracias
