### ISSUE TITLE
Lógica en Presentación de Series de Tiempo (Diapositivas 20,21,22)

### ISSUE THREAD

**Issue by ZeinDaher10** [sbohorquez/Econometria2#86]
Buenas noches profe,

Esto es solo una apreciación personal.

En la diapositiva 20 se habla de procesos NO estacionarios y se mencionan 3 casos particulares a trabajar a continuación, sin embargo, inmediatamente después (en las diapositivas 21 y 22) se menciona un ejemplo de un proceso estacionario en tendencia. Esto puede confundir al lector o al estudiante, pues este está esperando mayor profundización en:
El parámetro del proceso AR(1) es sesgado hacia cero.
El parámetro puede tener una distribución no-normal.
Obtenemos regresiones espurias.

Y el orden de la presentación ejemplifica procesos estacionarios en tendencia y luego el concepto de paseo aleatorio.

Probablemente cambiar el orden podría ser buena idea pero como digo, esta es solo una apreciación.

**Comment by sbohorquez** [comment]
Hola, si es un poco confuso, le cambie el titulo a procesos con tendencia determinítica para que sea más claro que el proceso es no estacionario.
