### ISSUE TITLE
estacionareidad débil

### ISSUE THREAD

**Issue by camilahm2022** [sbohorquez/Econometria2#88]
Buenas tardes profe!
Tengo una duda con respecto a la estacionaridad débil, en el principio de la temática hablamos de que existe estacionariedad débil cuando una variable necesita alguna restricción para poder volverse estacionaria pero, pero cuando vemos MA(1) nos comentan que para cualquier valor de teta el proceso es estacionario débil ya que no se deben imponer restricciones sobre el parámetro para obtener la varianza.

En este caso se vería distinto? o existe algún error en mi definición de estacionariedad débil

Feliz día!

**Comment by sbohorquez** [comment]
Hola, el proceso es estacionario debil cuando o cumple con la condición impuesta o no tiene condiciones, por ejemplo el AR(1) es estacionario si y solo si |phi| es menor a 1, pero el MA(1) siempre es estacionario porque no tienen condición.
