### ISSUE TITLE
Corrección diapositiva modelos dinámicos con variables exógenas

### ISSUE THREAD

**Issue by lmdiazm** [sbohorquez/Econometria2#89]
Buen día profe, no olvidar corregir el '#' que aparece en la diapositiva 47.

<img width="1677" alt="Captura de Pantalla 2022-03-16 a la(s) 10 34 43 a  m" src="https://user-images.githubusercontent.com/98715086/158628376-2384a927-90cc-4a94-8da6-63f5dc9861ba.png">

**Comment by sbohorquez** [comment]
Se hizo la corrección, gracias.
