### ISSUE TITLE
Duda sobre predicción modelo ARMAX

### ISSUE THREAD

**Issue by CarlosAndresRamosOspina** [sbohorquez/Econometria2#90]
En caso de que el valor de zt+1 no sea conocido, una opción es estimar un modelo de predicción para esta variable. Si en la misma diapositiva (diapositiva 40, modelos dinámicos con variables exógenas) nos advierte que este procedimiento aumenta la complejidad del problema, no se prestaría también para afectar la precisión de la predicción?

**Comment by sbohorquez** [comment]
Hola, si se aumenta la complejidad y la `precisión se ve afectada porque hay un error de predicción de z_t
