### ISSUE TITLE
Corrección redacción presentación Series de Tiempo

### ISSUE THREAD

**Issue by pzapatao** [sbohorquez/Econometria2#93]
En la diapositiva 26 en la sección de procesos estacionarios en tendencia, el último párrafo presente allí tiene un punto de por medio. Si se cambia este punto por una coma y la letra (Y) en minúscula seguida, le da más sentido al párrafo.

Quedaria asi: "A este tipo de procesos se les conoce como procesos estacionarios en tendencia, y es común su uso para filtros en economía."

**Comment by sbohorquez** [comment]
Se hizo la corrección, gracias
