### ISSUE TITLE
Correción redacción presentación modelos dinamicos variables exg

### ISSUE THREAD

**Issue by pzapatao** [sbohorquez/Econometria2#94]
Diapositiva 16, uso de coma innecesario y tilde en la palabra término.

Quedaria asi:
"Si los regresores afectan xt a través de rezagos distribuidos y si el término de error refleja la influencia de las variables omitidas, entonces es de esperar que estas variables omitidas también afecten xt a través de unos rezagos distribuidos"

**Comment by sbohorquez** [comment]
Se hizo la corrección, gracias
