### ISSUE TITLE
Error en la diapositiva 40

### ISSUE THREAD

**Issue by jpgomezm1** [sbohorquez/Econometria2#96]
Esta mal escrito el enunciado por lo que no es clara la idea, "En caso de que el valor de zt+1 no sea conocido, una opción es estimar modelo de predicción para esta variable. Este enfoque causa que el grado de complejidad del problema a resolver aumente, ya que necesitamos encontrar dos modelos.". El enunciado es este y falta el conector "el" en el principio del enunciado.

**Comment by sbohorquez** [comment]
Se hizo la corrección, gracias
