### ISSUE TITLE
Corrección Diapositiva Repaso MCG

### ISSUE THREAD

**Issue by pzapatao** [sbohorquez/Econometria2#98]
En la página número 8, se debe corregir el párrafo número 3.
Se debe corregir la palabra dudosa por dudoso para que quede coherente.

Quedaría de la siguiente forma:
Este supuesto es "dudoso" en aplicaciones de serie de tiempo, ya que esto requiere que no exista correlación entre diferentes periodos de tiempo.

**Comment by sbohorquez** [comment]
Se hizo la corrección, gracias
